# Generated by Django 3.0.8 on 2020-08-11 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DateTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_year', models.IntegerField()),
                ('date_month', models.IntegerField()),
                ('date_day', models.IntegerField()),
                ('time_hour', models.IntegerField()),
                ('time_minute', models.IntegerField()),
                ('time_second', models.IntegerField()),
            ],
        ),
    ]
